openapi: 3.0.2
info:
  title: API сервер для учебного проекта «Шесть городов (простой)».
  description: |-
    * Список ресурсов и маршрутов сервера «Шесть городов».
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
tags:
  - name: user
    description: Действия с пользователями
  - name: offers
    description: Действия с предложениями
  - name: comments
    description: Действия с комментариями

paths:
  /offers:
    get:
      tags:
      - offers
      summary: Получить список предложений
      description: Возвращает массив предложений. Каждое предложение описано в виде объекта.

      responses:
        "200":
          description: "Массив предложений до 60 шт."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offers'
    post:
      tags:
      - "offers"
      summary: Создать новое предложение
      description: Добавляет новое предложение от пользователя и возвращает его в виде созданного объекта
      requestBody:
        description: Информация для добавления новго предложения по аренде
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createOffer'
      responses:
        "201":
          description: "Предложение создано"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offerById'

  /offers/{offerId}:
    get:
      tags:
        - "offers"
      summary: Получить данные конкретного предложения
      description: Возвращает данные конкретного предложения по его id

      responses:
        "200":
          description: Возвращает объект запрашиваемого предложения
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offerById'
        "404":
          description: Запрашиваемое предложение не найдено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
    patch:
      tags:
        - "offers"
      summary: Редактирование предложения
      description: Редактирует конкретное предложение по его id
      requestBody:
        description: Объект с изменяемыми данными
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createOffer'
      responses:
        "201":
          description: Предложение отредактировано
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offerById'
        "404":
          description: Редактируемое предложение не найдено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
    delete:
      tags:
        - "offers"
      summary: Удаление предложения
      description: Удаляет конкретное предложение по его id
      responses:
        "204":
          description: Предложение удалено
        "404":
          description: Удаляемое предложение не найдено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'

  /user/register:
    post:
      tags:
      - "user"
      summary: Создание нового пользователя
      description: Создает нового пользователя
      requestBody:
        description: Информация необходимая для создания пользователя
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUser'
      responses:
        "201":
          description: Новый пользователь создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "409":
          description: Пользователь уже зарегистрирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/conflictError'

components:
  schemas:
    offers:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            example: '647b1d14c28f56fecbc86605'
          name:
            type: string
            example: 'Scarlet Horizon Hotel'
          description:
            type: string
            example: 'Located in front of the Montparnasse Tower and Galeries Lafayette Shopping Center, the Waldorf hotel offers air-conditioned rooms with free Wi-Fi.'
          publishDate:
            type: string
            example: '2023-06-02T10:59:12.838Z'
          city:
            type: string
            example: 'Cologne'
          prevImageUrl:
            type: string
            example: 'https://loremflickr.com/640/480/city'
          photos:
            type: array
            example: [
              'https://loremflickr.com/640/480/city',
              'https://loremflickr.com/640/480/city',
              'https://loremflickr.com/640/480/city',
              'https://loremflickr.com/640/480/city',
              'https://loremflickr.com/640/480/city',
              'https://loremflickr.com/640/480/city'
            ]
            minItems: 6
            maxItems: 6
          isPremium:
            type: boolean
            example: true
          rating:
            type: number
            example: 3.2
          housingType:
            type: string
            example: 'house'
          roomCount:
            type: number
            example: 6
          guestCount:
            type: number
            example: 9
          price:
            type: number
            example: 28383
          facilities:
            type: array
            example: [ 'Towels', 'Fridge' ]
          authorId:
            type: string
            example: '647b1d14c28f56fecbc86603'
          commentCount:
            type: number
            example: 17
          coordinates:
            type: object
            example: { longtitude: '50.708986', latitude: '6.758071' }

    offerById:
      type: object
      properties:
        id:
          type: string
          example: '647b1d14c28f56fecbc86605'
        name:
          type: string
          example: 'Summer Flower Hotel'
        description:
          type: string
          example: 'Located in front of the Montparnasse Tower and Galeries Lafayette Shopping Center, the Waldorf hotel offers air-conditioned rooms with free Wi-Fi.'
        publishDate:
          type: string
          example: '2023-06-04T12:20:12.838Z'
        city:
          type: string
          example: 'Cologne'
        prevImageUrl:
          type: string
          example: 'https://loremflickr.com/640/480/city'
        photos:
          type: array
          example: [
            'https://loremflickr.com/640/480/city',
            'https://loremflickr.com/640/480/city',
            'https://loremflickr.com/640/480/city',
            'https://loremflickr.com/640/480/city',
            'https://loremflickr.com/640/480/city',
            'https://loremflickr.com/640/480/city'
          ]
        isPremium:
          type: boolean
          example: false
        rating:
          type: number
          example: 3.2
        housingType:
          type: string
          example: 'house'
        roomCount:
          type: number
          example: 6
        guestCount:
          type: number
          example: 9
        price:
          type: number
          example: 13403
        facilities:
          type: array
          example: [ 'Towels', 'Fridge' ]
        coordinates:
          type: object
          example: { longtitude: '50.708986', latitude: '6.758071' }
        author:
          type: object
          example:  {
            name: 'Алина',
            email: 'trougrosoipipou-3867@yopmail.com',
            avatarUrl: 'https://avatarko.ru/img/kartinka/16/devushka_15972.jpg',
            isPro: false
          }

    createOffer:
      type: object

      properties:
        name:
          type: string
          example: 'Modest Landscape Resort'
          minLength: 10
          maxLength: 100
          required:
            - "true"

        description:
          type: string
          example: 'All soundproofed guest rooms include a 43-inch flat-screen TV (43 in) with cable channels and free Wi-Fi access. Each room has a simple décor and a hairdryer in the private bathroom.'
          minLength: 20
          maxLength: 1024
          required:
            - "true"

        publishDate:
          type: string
          example: '2023-05-21T09:52:29.036Z'
          required:
            - "true"

        city:
          type: string
          example: 'Paris'
          required:
            - "true"

        prevImageUrl:
          type: string
          example: 'https://loremflickr.com/640/480/city'
          required:
            - "true"

        photos:
          type: array
          example: [
            'https://loremflickr.com/640/480/city',
            'https://loremflickr.com/640/480/city',
            'https://loremflickr.com/640/480/city',
            'https://loremflickr.com/640/480/city',
            'https://loremflickr.com/640/480/city',
            'https://loremflickr.com/640/480/city'
          ]
          minItems: 6
          maxItems: 6

        isPremium:
          type: boolean
          example: true
          required:
            - "true"

        rating:
          type: number
          example: 4
          minimum: 1
          maximum: 5
          required:
            - "true"

        housingType:
          type: string
          example: 'apartment'
          required:
            - "true"

        roomCount:
          type: number
          example: 5
          minimum: 1
          maximum: 8
          required:
            - "true"

        guestCount:
          type: number
          example: 4
          minimum: 1
          maximum: 10
          required:
            - "true"

        price:
          type: number
          example: 3980
          minimum: 100
          maximum: 100000
          required:
            - "true"

        facilities:
          type: array
          example: [
            Towels,
            Fridge
          ]
          required:
            - "true"

        user:
          type: object
          example: {
            name: 'Тимофей',
            email: 'keijoissadedda-7159@yopmail.com',
            avatarUrl: https://avatarko.ru/img/kartinka/27/igra_Lara_Croft_26762.jpg,
            isPro: true
          }

        coordinates:
          type: object
          example: {
            longtitude: '48.701748',
            latitude: '2.236261'
          }
          required:
            - "true"

    NotFoundError:
      type: object
      properties:
        message:
          type: string
          example: 'Запрашиваемое предложение не найдено, проверьте id предложения и попробуйте еще раз'

    createUser:
      type: object
      properties:
        name:
          type: string
          example: Тимофей
          required:
            - "true"
        email:
          type: string
          example: timofeyinthebox@mail.net
          required:
            - "true"
        password:
          type: string
          example: 12345admin
          required:
            - "true"
        avatarUrl:
          type: string
          example: https://avatarko.ru/img/kartinka/27/igra_Lara_Croft_26762.jpg
        isPro:
          type: boolean
          example: false
          required:
            - "true"

    user:
      properties:
        name:
          type: string
          example: Тимофей
        email:
          type: string
          example: timofeyinthebox@mail.net
        avatarUrl:
          type: string
          example: https://avatarko.ru/img/kartinka/27/igra_Lara_Croft_26762.jpg
        isPro:
          type: boolean
          example: false

    conflictError:
      properties:
        message:
          type: string
          example: 'Нельзя выполнить так как уже существует'


